- name: Upload images to Supabase
  env:
    SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
    SUPABASE_BUCKET: ${{ secrets.SUPABASE_BUCKET }}

    SERIES_EN_URL: ${{ secrets.SERIES_EN_URL }}
    SERIES_AR_URL: ${{ secrets.SERIES_AR_URL }}

  run: node scripts/upload-to-supabase.js
